spring:
  dataSource:
    username: root
    password: sujung9300
    url: jdbc:mysql://localhost:3306/mongddang
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt-token:
  issue-key: longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong # 64글자 이상
  valid-time: 300000 # 5분
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml